In [7]:
import numpy as np

In [8]:
my_list = [1,2,3]

In [9]:
list_arr = np.array(my_list)        #casting a list into array 
print(list_arr.dtype)

int64


In [13]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3)              #creates an array with numbers from a uniform distribution

array([0.69162283, 0.6337861 , 0.90911792])

In [40]:
np.random.randn(5)             #values are in normal distributin (mean = 0, varience = 1)

array([ 0.87925766,  0.52379994, -0.13943789,  0.34796272, -0.09470222])

In [41]:
np.random.randn(2,2)

array([[-0.66262951, -0.78360104],
       [ 1.3604356 , -0.98845877]])

In [39]:
np.random.randint(0,101,2)

array([ 7, 98], dtype=int32)

In [43]:
np.random.seed(24)
np.random.rand(4)

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 ])

In [47]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [46]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [57]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([ 14,  61,  61,  46,  61,  50,  54,  63,   2, 100], dtype=int32)

In [63]:
ranarr.max()

np.int32(100)

In [64]:
ranarr.min()

np.int32(2)

In [65]:
ranarr.argmax()

np.int64(9)

In [66]:
ranarr.argmin()

np.int64(8)

In [67]:
ranarr.dtype

dtype('int32')

In [68]:
arr.shape

(25,)

In [69]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)